version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build checks"
      - npm test || true
  build:
    commands:
      - echo "Packaging application for deployment"
      - mkdir -p scripts
      - chmod +x scripts/*.sh
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/**/*
    - package.json
    - package-lock.json
    - server.js
    - .env
  base-directory: .
  discard-paths: no