version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Setting up environment variables"
      - echo "REACT_APP_BACKEND_URL=http://$BACKEND_URL:3002" >> .env
      - echo "REACT_APP_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
      - echo "REACT_APP_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID" >> .env
      - echo "REACT_APP_COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID" >> .env
      - echo "Running tests"
      - npm test || true
  build:
    commands:
      - echo "Building React application"
      - npm run build
      - echo "Preparing for deployment"
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync build/ s3://${S3_BUCKET_NAME} --delete
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  files:
    - build/**/*
  base-directory: build
  discard-paths: no

cache:
  paths:
    - node_modules/**/*